[package]
name = "tower-defense"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "=0.19.1", features = ["dynamic_linking"] }
serde = { version = "1", features = ["derive"]}
ron = "0.12"
bevy_common_assets = { version = "0.17", feature = ["ron"]}
bevy_rand = { version = "0.15", features = ["wyrand"]}
directories = "6"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[release]
lto = "thin"
codegen-units = 1
